name: Sync Shopify on CSV update

on:
  push:
    paths:
      - 'csv-input/visiotech.csv'
    branches:
      - master

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests

    - name: Run sync script
      run: python sync_visiotech.py
