name: Sync Shopify on CSV update

on:
  push:
    paths:
      - 'csv-input/visiotech.csv'
    branches:
      - master
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install pandas requests

    - name: Run sync script
      env:
        SHOP_URL: ${{ secrets.SHOP_URL }}
        SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
      run: python sync_visiotech.py
